Redservbot/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('botcreate.urls')),
]

botcreate/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="bot"

urlpatterns = [
    #==================Index========================
    path('', views.login, name='login'),
    path('loginProcess', views.loginProcess, name='loginProcess'),
    path('logout', views.logout, name='logout'),
    path('index.html', views.index, name='index'),
    path('history.html/<int:param>/', views.history, name='history'),
    path('historyview.html/<int:param>/', views.history_viewpage, name='history_viewpage'),
    path('botviewquery.html', views.botviewquery, name='botviewquery'),
    path('create.html',views.createbot,name='create'),
    path('editbot.html/<int:param>/',views.editbot, name='editbot'),
    path('getfile.html/<int:param>/',views.file_download, name='getfile'),
    path('getfilenameslist.html/<int:param>/',views.file_getfilenamelist, name='getfilenameslist'),

    #================Bot Monitor===========================
    #path('botmonitor.html',views.mail_admin,name='botmonitor'),
    path('botmonitor.html',views.botMonitor,name='botmonitor'),


    #===================Bot View===========================
    path('botview_getfile.html/<int:param>/',views.botview_file_download, name='botview_getfile'),
    path('botview_getfilenameslist.html/<int:param>/',views.botview_file_getfilenamelist, name='botview_getfilenameslist'),
    path('downloadreport.html',views.downloadreport, name='downloadreport'),
    path('mailreport.html',views.mailreport, name='mailreport'),
   #====================Chart View===========================

    path('mailchart.html',views.chart_mail,name='mailchart'),
    path('mailchart2.html',views.chart_mail2,name='mailchart2'),
    path('chart.html',views.sample_bar_chart,name='chartview'),
    path('changechart.html',views.changeChart,name='changechartview'),

]

botcreate/views.py
import datetime
import shutil
import smtplib
from datetime import date
import os
import zipfile
from email.mime.application import MIMEApplication
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import json
from urllib.parse import quote
import requests



import xlwt
from django.db import connection
from django.db.models import Q, IntegerField, Max
from django.db.models.functions import Cast
from openpyxl import Workbook
from tablib import Dataset
import sqlite3

from .Bot.History import BotHistory
from .Bot.sqlite import sqlite
from .models import Bot, Process, Subprocess, Workstatus, Botstatus, Kaizenstatus, Kaizenawardedyear, Developermail, \
    Mailreport_to, Mailreport_cc, dbMailrecipient, BotHist, CastAsInteger, TicketTrackingTable
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.utils.dateparse import parse_date

import pyodbc
import logging
logger = logging.getLogger('django')

import pandas as pd

from .tasks import mail_admin


# Create your views here.

def mail_admin(self):
    from datetime import datetime
    import time
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    import smtplib
    from botcreate.models import Bot
    import logging
    from selenium.webdriver.chrome.options import Options
    from selenium import webdriver
    from email.mime.application import MIMEApplication
    from email.mime.image import MIMEImage

    logger = logging.getLogger(__name__)

    message = "Please find the attached Daily Automation Report (01-July-2023 to 30-September-2023 - Q2)"

    logger.info("Testing")

    # =========================================================ChartPreparation======================================

    tickettrackingtable = TicketTrackingTable.objects.all().values()

    #for ticketTracking in tickettrackingtable:
        #print(ticketTracking)

    '''
    options = Options()
    options.headless = False  # Run Chrome in headless mode

    url = "http://172.26.1.19:85/bot/mailchart.html"
    # url = "http://127.0.0.1:8000/bot/mailchart.html"

    driver = webdriver.Chrome(executable_path="E:\\chromedriver.exe", options=options)
    # driver = webdriver.Chrome(executable_path="D:\\chromedriver.exe", options=options)

    driver.get(url)

    # Wait for the chart to be generated (replace "chart-element-id" with the actual ID of the chart element)
    chart_element = driver.find_element_by_id("mailchartcontainer")

    time.sleep(3)

    chart_image = chart_element.screenshot_as_png

    with open(settings.MEDIA_ROOT + "\\chart.png", "wb") as f:
        f.write(chart_image)

        # ===================================Chart2==========================================

        url = "http://172.26.1.19:85/bot/mailchart2.html"
        # url = "http://127.0.0.1:8000/bot/mailchart2.html"

        driver = webdriver.Chrome(executable_path="E:\\chromedriver.exe", options=options)
        # driver = webdriver.Chrome(executable_path="D:\\chromedriver.exe", options=options)

        driver.get(url)

        # Wait for the chart to be generated (replace "chart-element-id" with the actual ID of the chart element)
        chart_element = driver.find_element_by_id("mailchartcontainer")

        time.sleep(3)

        chart_image = chart_element.screenshot_as_png

        with open(settings.MEDIA_ROOT + "\\chart2.png", "wb") as f:
            f.write(chart_image)
    
    '''

    # ==============================================================Q4 Starts======================================================
    from_date_q4 = "2024-01-01"
    to_date_q4 = "2024-03-31"

    #from_date_q4 = datetime.strptime(from_date_q4, "%Y-%m-%d")
    #to_date_q4 = datetime.strptime(to_date_q4, "%Y-%m-%d")


    New_Bots_q4 = TicketTrackingTable.objects.filter(
        Q(startdate__range=(from_date_q4, to_date_q4)) | Q(enddate__range=(from_date_q4, to_date_q4)),
        status__in=["Gone live"],projecttype='Automation').order_by('developermailid')

    Enh_Bots_q4 = TicketTrackingTable.objects.filter(
        Q(enhancestartdate__range=(from_date_q4, to_date_q4)) | Q(enhanceenddate__range=(from_date_q4, to_date_q4)),
        status__in=["Gone live"],projecttype='Automation').order_by('developermailid')

    rest_Bots_q4 = TicketTrackingTable.objects.filter(
        Q(creationdate__range=(from_date_q4, to_date_q4)) | Q(startdate__range=(from_date_q4, to_date_q4)) | Q(
            enddate__range=(from_date_q4, to_date_q4)) | Q(enhancestartdate__range=(from_date_q4, to_date_q4)) | Q(
            enhanceenddate__range=(from_date_q4, to_date_q4)),
        status__in=["Yet to Start", "WIP", "UAT"],projecttype='Automation').order_by('developermailid')

    excel_reports_q4 = TicketTrackingTable.objects.filter(
        Q(creationdate__range=(from_date_q4, to_date_q4)) | Q(startdate__range=(from_date_q4, to_date_q4)) | Q(
            enddate__range=(from_date_q4, to_date_q4)) | Q(enhancestartdate__range=(from_date_q4, to_date_q4)) | Q(
            enhanceenddate__range=(from_date_q4, to_date_q4)),projecttype='Automation').order_by('developermailid')

    table_row_data_q4 = ""
    enhance_table_row_data_q4 = ""
    rest_row_data_q4 = ""

    if New_Bots_q4.exists():

        for obj in New_Bots_q4:

            Botno = obj.projectno
            Businessunit = obj.businessunit
            Botname = obj.projectname
            Botdesc = obj.projectdesc
            Process = obj.process
            Subprocess = obj.subprocess
            Spocname = obj.spocname

            Startdate = ""
            if obj.startdate:
                Startdate = datetime.strptime(str(obj.startdate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            Enddate = ""
            if obj.enddate:
                Enddate = datetime.strptime(str(obj.enddate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            enhancestartdate = ""
            if obj.enhancestartdate:
                enhancestartdate = datetime.strptime(str(obj.enhancestartdate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            enhanceenddate = ""
            if obj.enhanceenddate:
                enhanceenddate = datetime.strptime(str(obj.enhanceenddate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            Botstatus = obj.status
            Developermail = obj.developermailid

            manualtimetaken = ""
            if obj.manualtime and str(obj.manualtime) != "None":
                manualtimetaken = obj.manualtime

            bottimetaken = ""
            if obj.automationtime and str(obj.automationtime) != "None":
                bottimetaken = obj.automationtime

            totaltimesave = ""
            mandaysaved = ""
            if obj.totaltime and str(obj.totaltime) != "None":
                totaltimesave = obj.totaltime

                if "mins" in str(totaltimesave) and "days" not in str(totaltimesave):
                    mandaysaved = round(int(str(totaltimesave).replace("mins", "")) / 60)
                    if mandaysaved <= 8:
                        mandaysaved = str(mandaysaved) + " hrs"
                    else:
                        mandaysaved = str(round(mandaysaved / 8)) + " Business days"
                else:
                    mandaysaved = totaltimesave

            table_row_data_q4 = table_row_data_q4 + "<tr><td><a style='color:black' href='http://172.26.1.19:85/bot/editbot.html/" + str(
                Botno) + "'>" + str(Botno) + "</a></td><td>" + str(
                Businessunit) + "</td><td style='white-space:nowrap';>" + str(Botname) + "</td><td>" + str(
                Botdesc) + "</td><td>" + str(
                Spocname) + "</td><td style='color:green'>" + str(
                manualtimetaken) + "</td><td style='color:green'>" + str(
                totaltimesave) + "</td><td style='color:green'>" + str(mandaysaved) + "</td><td>" + str(
                Developermail) + "</td><td>" + str(Subprocess) + "</td><td>" + str(
                Startdate) + "</td><td>" + str(
                Enddate) + "</td><td>" + str(enhancestartdate) + "</td><td>" + str(
                enhanceenddate) + "</td><td>" + str(Botstatus) + "</td><td>"


    else:
        table_row_data_q4 = "No_data"

    if Enh_Bots_q4.exists():

        for obj in Enh_Bots_q4:

            Botno = obj.projectno
            Businessunit = obj.businessunit
            Botname = obj.projectname
            Botdesc = obj.projectdesc
            Process = obj.process
            Subprocess = obj.subprocess
            Spocname = obj.spocname

            Startdate = ""
            if obj.startdate:
                Startdate = datetime.strptime(str(obj.startdate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            Enddate = ""
            if obj.enddate:
                Enddate = datetime.strptime(str(obj.enddate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            enhancestartdate = ""
            if obj.enhancestartdate:
                enhancestartdate = datetime.strptime(str(obj.enhancestartdate), "%Y-%m-%d %H:%M:%S%z").strftime(
                    "%d-%m-%Y")

            enhanceenddate = ""
            if obj.enhanceenddate:
                enhanceenddate = datetime.strptime(str(obj.enhanceenddate), "%Y-%m-%d %H:%M:%S%z").strftime("%d-%m-%Y")

            Botstatus = obj.status
            Developermail = obj.developermailid

            manualtimetaken = ""
            if obj.manualtime and str(obj.manualtime) != "None":
                manualtimetaken = obj.manualtime

            bottimetaken = ""
            if obj.automationtime and str(obj.automationtime) != "None":
                bottimetaken = obj.automationtime

            totaltimesave = ""
            mandaysaved = ""

botcreate/templates/bot/chart.html
<!-- index.html -->
{% load static %}
<html>
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Automation</title>

    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Pretty-Registration-Form.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.3/css/dataTables.bootstrap5.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <style>

        #example

        #tabledata{
        overflow: auto;
        }

        .paginate_button{
         background-color: #4CAF50; /* Green */
         border: none;
         color: white;
         padding: 5px 5px;
         text-align: center;
         text-decoration: none;
         display: inline-block;
         font-size: 12px;
         margin:10px;
         }

        #example_paginate{
        text-align:left
        }

        th{
        font-size:10px;
        }

        #example_filter{
        color:green;
        font-size: 13px;
        }

        #example_length{
        color:green;
        font-size: 13px;
        }

        #example_info{
        color:green;
        font-size: 13px;
        }

        .odd,.even{
        background-color:white;
        font-size:12px;
        }

        table.dataTable tbody tr td {
        word-wrap: normal;
        word-break: keep-all;
        }

        table.dataTable thead tr th {
        min-width: 80px !important;
        padding-top: 0px !important;
        height:20px !important;

        }

        .navbar{
        background-color: #8BD182;
        padding:0px;
        }

    </style>

<script>

    $(document).ready(function(){

         $('#fromdate').datepicker({
          format: 'dd/mm/yyyy',
          orientation: 'bottom auto'
          });
          $('#todate').datepicker({
          format: 'dd/mm/yyyy',
          orientation: 'bo#8BD182 to'

          });
          $('#enddate').datepicker({
          format: 'dd/mm/yyyy',
          orientation: 'bottom auto'

          });

          $('#example').DataTable();


        });


     function validateForm()
     {

          var selectedValues = $('#dropdownselect').val();
          $('#hiddenInput').val(selectedValues);

          document.getElementById('chart').submit();

     }

</script>


<script>
    window.onload = function () {


    if("{{chartview}}"=="businessunitbar"){

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: "Automation"
	},
	axisY: {
		title: "Number Of Bots",
		titleFontColor: "green",
		lineColor: "green",
		labelFontColor: "green",
		tickColor: "#4F81BC"
	},

	toolTip: {
		shared: true
	},
	legend: {
		cursor:"pointer",
		itemclick: toggleDataSeries
	},
	data: [{
		type: "column",
		indexLabel:"{y}",
		name: "RGS",
		legendText: "RGS",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints1|safe }}
	},
	{
		type: "column",
		indexLabel:"{y}",
		name: "RGF",
		legendText: "RGF",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints2|safe }}
	},

	{
		type: "column",
		indexLabel:"{y}",
		name: "Wabco",
		legendText: "Wabco",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints3|safe }}
	}

	]
});


chart.render();

function toggleDataSeries(e) {
	if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
		e.dataSeries.visible = false;
	}
	else {
		e.dataSeries.visible = true;
	}
	chart.render();
}


}








if("{{chartview}}"=="teambar"){

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: "Automation"
	},
	axisY: {
		title: "Number Of Bots",
		titleFontColor: "green",
		lineColor: "green",
		labelFontColor: "green",
		tickColor: "#4F81BC"
	},

	toolTip: {
		shared: true
	},
	legend: {
		cursor:"pointer",
		itemclick: toggleDataSeries
	},
	data: [{
		type: "column",
		indexLabel:"{y}",
		name: "Prajnya",
		legendText: "Prajnya",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints1|safe }}
	},
	{
		type: "column",
		indexLabel:"{y}",
		name: "Prasanth",
		legendText: "Prasanth",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints2|safe }}
	},
	{
		type: "column",
		indexLabel:"{y}",
		name: "Santhosh",
		legendText: "Santhosh",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints3|safe }}
	}
	,
	{
		type: "column",
		indexLabel:"{y}",
		name: "Thanis",
		legendText: "Thanis",
		axisYType: "primary",
		showInLegend: true,
		dataPoints:{{ datapoints4|safe }}
	}

	]
});


chart.render();

function toggleDataSeries(e) {
	if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
		e.dataSeries.visible = false;
	}
	else {
		e.dataSeries.visible = true;
	}
	chart.render();
}


}



        if("{{chartview}}"=="bar"){

        var chart = new CanvasJS.Chart("chartContainer", {
          animationEnabled: true,
          exportEnabled: true,
          title:{
            text: "Automation",
            fontFamily: "Tahoma"
          },
          axisY: {
            title: ""
          },
          data: [{
            type: "column",
            indexLabel:"{y}",
            yValueFormatString: "#,##0",
            dataPoints: {{ datapoints1|safe }}
          }]
        });
        chart.render();
        }


        if("{{chartview}}"=="pie"){
              var chart = new CanvasJS.Chart("chartContainer", {
              exportEnabled: true,
              animationEnabled: true,
              title: {
                text: "Automation"
              },
              data: [{
                type: "pie",
                legendText: "{label}",
                yValueFormatString: "#,###\"\"",
                indexLabel: "{label} ({y})",
                dataPoints: {{ bot_data|safe }}
              }]
            });
            chart.render();
        }
    }


</script>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a href="{% url 'bot:index' %}" class="navbar-brand"><img src="{% static 'assets/img/Redserv.png' %}" width="100px" height="50px"></img></a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'bot:index' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'bot:botviewquery' %}" class="nav-item nav-link active">Botview</a>
                <a href="{% url 'bot:botmonitor' %}" class="nav-item nav-link active">Botmonitor</a>
                <a href="{% url 'bot:chartview' %}" class="nav-item nav-link active" tabindex="-1">Chartview</a>
                <a href="{% url 'bot:logout' %}"><button style="margin-left:720px;background-color:#AFE1AF;color:black" type="button" class="btn btn-success">Logout</button></a>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="#" class="nav-item nav-link"></a>
            </div>
        </div>
    </div>
</nav>
   <div class="row">

       <div class="col-md-2 offset-md-1">

        <select  class="form-select" id="dropdownselect" name="dropdownselect" style="width:175px;height:27px;font-size:12px" >
             <option value="All" style="font-size:12px" >All</option>

             {% if Developername == "Businessunit" %}
             <option value="Businessunit" style="font-size:12px" selected>BusinessUnit</option>
             {% else %}

             <option value="Businessunit" style="font-size:12px" >BusinessUnit</option>
             {% endif %}

             {% if Developername == "Team" %}
             <option value="Team" style="font-size:12px" selected>Team</option>
             {% else %}
             <option value="Team" style="font-size:12px" >Team</option>
             {% endif %}

             {% if Developername == "prajnya.sahu@redingtongroup.com" %}
             <option value="prajnya.sahu@redingtongroup.com" style="font-size:12px" selected>prajnya.sahu@redingtongroup.com</option>
             {% else %}
             <option value="prajnya.sahu@redingtongroup.com" style="font-size:12px" >prajnya.sahu@redingtongroup.com</option>
             {% endif %}

             {% if Developername == "prasanth.muruga@redingtongroup.com" %}
             <option value="prasanth.muruga@redingtongroup.com" style="font-size:12px" selected>prasanth.muruga@redingtongroup.com</option>
             {% else %}
             <option value="prasanth.muruga@redingtongroup.com" style="font-size:12px" >prasanth.muruga@redingtongroup.com</option>
             {% endif %}

            {% if Developername == "Swetha.M@Redingtongroup.com" %}
             <option value="Swetha.M@Redingtongroup.com" style="font-size:12px" selected>Swetha.M@Redingtongroup.com</option>
            {% else %}
             <option value="Swetha.M@Redingtongroup.com" style="font-size:12px" >Swetha.M@Redingtongroup.com</option>
            {% endif %}

            {% if Developername == "thanis.albert@redingtongroup.com" %}
            <option value="thanis.albert@redingtongroup.com" style="font-size:12px" selected>thanis.albert@redingtongroup.com</option>
            {% else %}
            <option value="thanis.albert@redingtongroup.com" style="font-size:12px" >thanis.albert@redingtongroup.com</option>
            {% endif %}

        </select>
        </div>


       <div class="col-md-2">
         <form id="chart" class="custom-form" style=""  method="POST" action="{% url 'bot:changechartview' %}" >
         {% csrf_token %}
          <input type="hidden"  name="fromdatenew" id="fromdatenew">
          <input type="hidden" name="todatenew" id="todatenew">
          <input type="hidden" id="hiddenInput" name="hiddenInput">
         <select onchange="return validateForm()"  class="form-select" id="chartselect" name="chartselect" style="width:175px;height:27px;font-size:12px">
           <option value="select" style="font-size:12px" selected>Select Chart</option>
           <option value="pie" style="font-size:12px" >Pie</option>
           <option value="bar" style="font-size:12px" >Bar</option>
         </select>
         </form>
       </div>


    </div>

    <div class="row">
    <div class="col-md-10" id="chartContainer" style="width:80%; height: 360px;">
    </div>
    <div class="col-md-2">Total Bots: {{Totalcount}} <br>
      {% if chartview == "teambar" %}
     <span style="color:#2187ab">Prajnya:</span> {{Prajnyacount}}<br> <span style="color:#ab2135">Prasanth:</span> {{Prasanthcount}}<br> <span style="color:#51be25">Santhosh:</span> {{Santhoshcount}}<br> <span style="color:#3bc5c1">Thanis:</span> {{Thaniscount}}
      {% endif %}

      {% if chartview == "businessunitbar" %}
     <span style="color:#2187ab">RGS:</span> {{Rgscount}}<br> <span style="color:#ab2135">RGF:</span> {{Rgfcount}}<br><span style="color:green">Wabco:</span> {{Wabcocount}}
      {% endif %}

    </div>

    </div>

    <div class="row">
    <div class="col-md-10" id="chartContainer2" style="width:80%; height: 360px;">
    </div>

    </div>

<script src="{% static 'assets/js/canvasjs.min.js' %}"></script>


</body>
</html>

botcreate/templates/bot/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/action_page.php" >
        {% csrf_token %}
        <input type="hidden"  name="fromdateview" id="fromdateview">
        <input type="hidden" name="todateview" id="todateview">
      <select name="choice" id="dropdownselect" name="dropdownselect" >
             <option value="Completed" >Select View</option>
             <option value="Completed" >Completed</option>
             <option value="Cancelled"  >Cancelled</option>
             <option value="User Testing & Dev Enhancement" >User Testing & Dev Enhancement</option>
             <option value="Under User Testing"  >Under User Testing</option>
             <option value="TM TO BE DONE" >TM TO BE DONE</option>
             <option value="Devolopment In Progress" >Devolopment In Progress</option>
             <option value="Bot No.Generated" >Bot No.Generated</option>
        </select>
      </form>

<form action="/action_page.php">
  <label for="cars">Choose a car:</label>
  <select name="cars" id="cars" multiple>
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
  <br><br>
  <input type="submit" value="Submit">
</form>



</body>
</html>